name: build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  LM_LICENSE_FILE: "${{ github.workspace }}/tools/cw/license.dat"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Install Software
        run: |
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
          sudo dpkg --add-architecture i386
          sudo apt-get update -y
          sudo apt-get install -y --install-recommends python3-pip ninja-build winehq-stable binutils-arm-none-eabi gcc-arm-none-eabi flex bison
          pip install --user meson pyelftools

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure Repo
        run: make configure

      - name: Build Repo
        run: make release

      - name: Build upload
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            build/pokeplatinum.us.nds
            build/main.nef.xMAP
          retention-days: 1
